dataset: ogbg-molhiv
aug: baseline
model_type: gnn-transformer
gnn_type: gin
gnn_virtual_node: false
graph_pooling: cls
runs: 5
seed: 3407
batch_size: 64
lr: 0.0001
start-eval: 1
scheduler: plateau

transformer_norm_input: true
gnn_dropout: 0.3
gnn_JK: cat

gnn_num_layer: 20
gnn_residual: true
num_encoder_layers: 16
epochs: 50