dataset: IMDB-BINARY
aug: baseline
model_type: gnn-transformer

gnn_type: gin
gnn_virtual_node: false

graph_pooling: cls

lr: 0.0001

seed: 3407

transformer_norm_input: true

runs: 5
epochs: 100

d_model: 128
dim_feedforward: 256
num_encoder_layers: 12
scheduler: cosine

transformer_dropout: 0.3
gnn_dropout: 0.1

gnn_num_layer: 16
gnn_residual: true
